# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "582c5d10501a8fedaf68ab259f35111e"
name = "My first app"
handle = "my-first-app-1725"
application_url = "https://dated-rhythm-club-tue.trycloudflare.com/auth/shopify"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "avadasaas-internnodejs.myshopify.com"

[auth]
redirect_urls = [
  "https://dated-rhythm-club-tue.trycloudflare.com/auth/shopify/callback",
  "https://dated-rhythm-club-tue.trycloudflare.com/authSa/shopify/callback",
  "https://dated-rhythm-club-tue.trycloudflare.com/auth/shopify/embed/callback",
  "https://dated-rhythm-club-tue.trycloudflare.com/auth/shopify/embed/callback/updateScopes",
  "https://localhost:3000/auth/shopify/callback",
  "https://localhost:3000/authSa/shopify/callback",
  "https://localhost:3000/auth/shopify/embed/callback"
]

[webhooks]
api_version = "2025-04"

[pos]
embedded = false
